app = "tianle-redis"
primary_region = "hkg"

[build]
image = "redis:3.2.8-alpine"

[mounts]
source = "redis_data"
destination = "/data"

[services]
internal_port = 6379
protocol = "tcp"

[[services.ports]]
port = 6379